// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxtwmnmhahkphkgeipwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4dHdtbm1oYWhrcGhrZ2VpcHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNDAxOTcsImV4cCI6MjA1MTcxNjE5N30.bvniFTiiMvfLZirrpgkndAdWp97PZUSO6ItMd0mXCoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);